version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twilio/sdk
    versions:
    - 6.16.1
    - 6.17.0
    - 6.18.0
    - 6.19.0
    - 6.20.0
    - 6.21.0
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
