language: php
php:
- 7.1
install:
- composer install
env:
  global:
    - APP_ENV=testing
    - APP_KEY=M0HYKpEoPSPnl7V4Ck6notarealkeyUx
before_script:
  - php Setup.php
  - php artisan migrate
  - php artisan db:seed
  - ./vendor/bin/phpcs --standard=twilio_ruleset.xml --extensions=php .
